### PR TITLE
Re-introduce Dynamic Noise Models

### PR DESCRIPTION
**Pull request by a-krawciw**
Add support for noise models that change based on the value of state variables.

Additionally, add a noise model for the projected and linearized covariance of landmarks into pixels for stereo cameras.

### CODE REVIEW

**Comment by keenan-burnett** [comment]
Looks good to me. Can you add an example for how to use `LandmarkNoiseEvaluator` ?

**Comment by keenan-burnett** [comment]
Also, can you squash your changes into a single commit?

**Comment by a-krawciw** [comment]
The squash happens when the approved pull request is merged, but I will do that.

**Comment by keenan-burnett** [comment]
Is this ready to merge yet?

**Pull request merged**
